[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "nodejs_18", "pnpm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pnpm install --no-frozen-lockfile",
    "cd compute && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && cd .."
]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"